In [6]:
import collections# from import OrderedDict
dict2 = {'sudha': '50', 'sunil': '11',
        'sanjeeth': '25', 'yogesh': '20', 'sooraj': '63'}
dict1 = OrderedDict(sorted(dict2.items()))
print(dict1)

OrderedDict([('sanjeeth', '25'), ('sooraj', '63'), ('sudha', '50'), ('sunil', '11'), ('yogesh', '20')])


In [11]:
import random
dict1 = {}
a, b, c = 1, 0, 9
dict1[a, b, c] = a + b - c;
a, b, c = 54, 24, 47
dict1[a, b, c] = a + b - c;
print(dict1)


{(1, 0, 9): -8, (54, 24, 47): 31}


In [14]:
Set1 = {(1, "cherry"), ( 2, 4), 3,}
print("Size of Set1: " + str(Set1.__sizeof__()))

Size of Set1: 200


In [17]:
set1 = set("python")
for val in set1:
	print(val)


h
o
p
y
n
t


In [ ]:
Assigning Subsequent Rows to Matrix first row elements

In [18]:

list1 = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("The original list : " + str(list1))
reg = {list1[0][a] : list1[a + 1] for a in range(len(list1) - 1)}

print("The Assigned Matrix : " + str(reg))


The original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [20]:
#adding two matrix
import numpy as np
x= np.array([[1, 2], [3, 4]])
y= np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(x)
print("Printing elements of second matrix")
print(y)
print("Addition of two matrix")
print(np.add(x, y))


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [21]:
# subtracting two matrix
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Subtraction of two matrix")
print(np.subtract(A, B))


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [22]:
import inspect
def fun(a, b):
    return a**b
print(inspect.signature(fun))


(a, b)
